### ISSUE TITLE
Model is underdetermined

### ISSUE THREAD

**Issue by Sunnyturicum** [brosaplanella/SPMe_SR#1]
Hi 

Thanks for making this code available. I was trying to make this code initially for 50 cycles to test and only for lithium plating running. 

What I changed in the run_experiment file is:
```
options = {
    #"SEI": "ec reaction limited",
     "SEI": "none",
    #"SEI porosity change": "true",
    "lithium plating": "irreversible",
    # "lithium plating": "none",
    "lithium plating porosity change": "true",
}

N_cycles = 50

```
After adapting the cycle number in run_RPT and it I got this error:
```RPT for SPMe+SR at 0.33C
Running RPT for cycle 1 of 50
Traceback (most recent call last):
  File "/content/SPMe_SR/run_RPT.py", line 35, in <module>
    df = run_RPT(sim, C_rate=C_rate, RPT_at_cycles=RPT_at_cycles)
  File "/content/SPMe_SR/auxiliary_functions.py", line 244, in run_RPT
    sim.solve()
  File "/usr/local/lib/python3.10/dist-packages/pybamm/simulation.py", line 600, in solve
    self.build_for_experiment(check_model=check_model, initial_soc=initial_soc)
  File "/usr/local/lib/python3.10/dist-packages/pybamm/simulation.py", line 444, in build_for_experiment
    built_model = self._disc.process_model(
  File "/usr/local/lib/python3.10/dist-packages/pybamm/discretisations/discretisation.py", line 157, in process_model
    model.check_well_posedness()
  File "/usr/local/lib/python3.10/dist-packages/pybamm/models/base_model.py", line 701, in check_well_posedness
    self.check_well_determined(post_discretisation)
  File "/usr/local/lib/python3.10/dist-packages/pybamm/models/base_model.py", line 802, in check_well_determined
    raise pybamm.ModelError("model is underdetermined (too many variables)")
pybamm.expression_tree.exceptions.ModelError: model is underdetermined (too many variables)
````

How can I solve this?

**Comment by brosaplanella** [comment]
Can you provide a minimum working example for the code (in this case I mean with the minimum number of cycles to reproduce the error)? Also, which PyBaMM version are you using?

**Comment by Sunnyturicum** [comment]
The minimum number of cycles to reproduce the error was 10. However, I also tried with 50 cycles. Below I have put the entire code.

run_experiment file:
```
import os
import pybamm
from auxiliary_functions import set_parameters, create_filename

pybamm.set_logging_level("NOTICE")

# Define models
options = {
    #"SEI": "ec reaction limited",
     "SEI": "none",
    #"SEI porosity change": "true",
    "lithium plating": "irreversible",
    # "lithium plating": "none",
    "lithium plating porosity change": "true",
}
SPMe = pybamm.lithium_ion.SPMe(name="SPMe+SR", options=options)
DFN = pybamm.lithium_ion.DFN(name="DFN+SR", options=options)

models = [SPMe, DFN]

# Define parameters
param = set_parameters()

# Define experiment
N_cycles = 50
save_at_cycles = [1]  # [1] by default to save memory
C_ch = 1 / 2
C_dch = 1

experiment = pybamm.Experiment(
    [
        (
            "Discharge at {}C until 2.5 V".format(C_dch),
            "Charge at {}C until 4.2 V".format(C_ch),
            "Hold at 4.2 V until C/20",
        )
    ]
    * N_cycles,
)

# Solve models
sims = []

for model in models:
    solver = pybamm.CasadiSolver("safe")
    sim = pybamm.Simulation(
        model,
        parameter_values=param,
        experiment=experiment,
        solver=solver,
    )
    sim.solve(save_at_cycles=save_at_cycles)
    filename = create_filename(model, C_dch, C_ch)
    # Hack to allow pickling
    # sim.op_conds_to_built_solvers = None
    sim.save(
        os.path.join(
            "data",
            "sim_" + filename + "_{}.pkl".format(N_cycles),
        )
    )
```
run_RPT file
```
import pybamm
import os
import gc
from auxiliary_functions import (
    create_filename,
    run_RPT,
    set_plotting_format,
    create_C_tag,
)

# Define plotting format
set_plotting_format()

# Define model options
N_cycles = 50
C_ch = 1 / 2
C_dch = 1
options = {"SEI": False, "plating": True, "porosity": True}
RPT_at_cycles = 10
sims = ["SPMe_SR", "DFN_SR"]
C_rates = [1 / 3]

for name in sims:
    sim = pybamm.load_sim(
        os.path.join(
            "data",
            "sim_"
            + create_filename({"name": name, **options}, C_dch, C_ch)
            + "_{}.pkl".format(N_cycles),
        )
    )
    for C_rate in C_rates:
        print("RPT for {} at {:.2f}C".format(sim.model.name, C_rate))
        df = run_RPT(sim, C_rate=C_rate, RPT_at_cycles=RPT_at_cycles)

        df.to_csv(
            os.path.join(
                "data",
                "RPT_"
                + create_C_tag(C_rate)
                + "_"
                + create_filename(sim.model, C_dch, C_ch)
                + "_{}.csv".format(N_cycles),
            )
        )

        gc.collect()
```

**Comment by brosaplanella** [comment]
I tried and it works fine for me. Make sure you have the most recent `requirements.txt` installed as I changed them in the latest release.

**Comment by Sunnyturicum** [comment]
Thanks, I installed python version 3.8.17 in a separate environment. If I run the requirmenets.txt file I get this error:
```
Could not find a version that satisfies the requirement casadi==3.5.6 (from versions: 3.6.0, 3.6.1, 3.6.2, 3.6.3)
```
If I run a newer casadi versionn I get this error:
```
partially initialized module 'pybamm' has no attribute 'parameters' (most likely due to a circular import)
```

**Comment by brosaplanella** [comment]
Are you installing it from scratch or overriding your previous installation? If the latter, try installing from scratch.
